DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TEST: ('middle_down_wai_test',)
  TRAIN: ('middle_down_wai_train',)
INPUT:
  MAX_SIZE_TEST: 1280
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 720
  MIN_SIZE_TRAIN: (720,)
  RANDOM_FLIP: none
MODEL:
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.7
    NMS_THRESH_TEST: 0.3
  RESNETS:
    DEPTH: 50
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 56
  WEIGHTS: /DATA/models/保健版本/middle_down_wai/20230302/model_final.pth

OUTPUT_DIR: /mnt/dlData/EightModelOutputs/models/2022_03_21AM/middle_down_wai
SOLVER:
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 4
  MAX_ITER: 180000
  REFERENCE_WORLD_SIZE: 1
  STEPS: (120000,140000,160000)
TEST:
  EVAL_PERIOD: 2000
_BASE_: Base-Keypoint-RCNN-FPN.yaml
