DATALOADER:
  NUM_WORKERS: 2

DATASETS:
  TEST: ('middle_down_wai_test',)
  TRAIN: ('middle_down_wai_train',)

INPUT:
  MAX_SIZE_TEST: 1280
  MAX_SIZE_TRAIN: 1280
  # MIN_SIZE_TEST: 736
  # MIN_SIZE_TRAIN: (736,)
  RANDOM_FLIP: none

MODEL:
  RESNETS:
    DEPTH: 50

  ROI_KEYPOINT_HEAD:
    #全经络版本是90个点，调理版本是56
    NUM_KEYPOINTS: 90

  WEIGHTS: /home/zy/Downloads/model_final_a6e10b.pkl

OUTPUT_DIR: /mnt/dlData/EightModelOutputs/models/2022_03_21AM/middle_down_wai

SOLVER:
  BASE_LR: 0.01
  #batch size
  IMS_PER_BATCH: 2
  REFERENCE_WORLD_SIZE: 1
  STEPS: (16000,18000)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000


TEST:
  EVAL_PERIOD: 2000
_BASE_: Base-Keypoint-RCNN-FPN.yaml

#visible image in tensorboard per 1000 iter
# VIS_PERIOD: 1000