DATALOADER:
  NUM_WORKERS: 2

DATASETS:
  TEST: ('middle_down_wai_test',)
  TRAIN: ('middle_down_wai_train',)

INPUT:
  MAX_SIZE_TEST: 1280
  MAX_SIZE_TRAIN: 1280
  # MIN_SIZE_TEST: 736
  # MIN_SIZE_TRAIN: (736,)
  RANDOM_FLIP: none

MODEL:
  RESNETS:
    DEPTH: 50
  # PIXEL_MEAN: [141.584,147.873,152.721]
  # PIXEL_STD: [42.925,30.753,25.354]
  RPN:
    IN_FEATURES: ["p5"]
  ROI_HEADS:
    IN_FEATURES: ["p5"]
    BATCH_SIZE_PER_IMAGE: (128)
    IOU_THRESHOLDS: [0.7]
  ROI_BOX_HEAD:
    # Options are: "smooth_l1", "giou", "diou", "ciou"
    #在box_head 中精确回归
    BBOX_REG_LOSS_TYPE: "ciou"

  ROI_KEYPOINT_HEAD:
    #全经络版本是90个点，调理版本是56
    NUM_KEYPOINTS: 56
    #roi align 输出尺寸
    # POOLER_RESOLUTION: [14,14]
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: False
    LOSS_WEIGHT: 4.0
  ANCHOR_GENERATOR:
    SIZES: [[541]]
    #ratios = 2.0: h/w = 2   ratios = 0.5: h/w = 0.5
    ASPECT_RATIOS: [[0.5]]
  
  

  WEIGHTS: /home/zy/Downloads/model_final_a6e10b.pkl

OUTPUT_DIR: /mnt/dlData/EightModelOutputs/models/2022_03_21AM/middle_down_wai

SOLVER:
  BASE_LR: 0.01
  
  #batch size
  IMS_PER_BATCH: 2
  REFERENCE_WORLD_SIZE: 1
  STEPS: (16000,18000)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000


TEST:
  EVAL_PERIOD: 2000
_BASE_: Base-Keypoint-RCNN-FPN.yaml

#visible image in tensorboard per 1000 iter
# VIS_PERIOD: 1000